### ISSUE TITLE
Nested groups aren't synchronized

### ISSUE THREAD

**Issue by itrich** [garloff/ucs2mailman3#21]
I recently discovered that members of nested LDAP groups aren't synchronized to the corresponding mailing list.

How to reproduce:

1. Create LDAP group `foo`.
2. Add user `alice` to `foo`
3. Create LDAP group `bar`
4. Add user `bob` to `bar`
5. Add the group `foo` as member of `bar`.
6. Run `ucs2mailman.py -d -n -a ADMIN@DOMAIN -t MLDOMAIN -u udm.users -g udm.groups` 

The mailing list corresponding to group `bar` will only consist of member `bob`.

**Comment by garloff** [comment]
I see the group `foo` referenced as nestedGroup in group `bar`.
This not currently evaluated by the UCS/LDIF parser.

As for the expected result:
* Do you expect the mailing list that belongs to `foo` (if any) to be subscribed to the mailing list that belongs to `bar`
* Or you expect all members from `foo` to be directly subscribed to the mailing list belonging to `bar`?

I guess the latter option is more straight-forward -- we would have to add the individuals from `foo` as non-members otherwise to allow them to post, so we'd have to recurse down anyway ...

**Comment by itrich** [comment]
> * Or you expect all members from foo to be directly subscribed to the mailing list belonging to bar?

I also think that this is the more reasonable option. Nested groups should be flattened, so that members of sub-groups are directly subscribed to the parent's mailing list.

**Comment by garloff** [comment]
Hi Eduard,
your response is confusing me, sorry. Probably I did not word the options clearly.
Option 1 was to subscribe MLs to MLs when confronted with nestedGroups. 
Option 2 was to subscribe the members from nestedGroups directly to the ML.
You quoted option 1 and then said you would flatten and directly subscribe (which is option 2).
I suspect you prefer option 2 and I have the same tendency.
(As we have a unidirectional sync LDAP/UCS to MailMan, there are few advantages of reflecting the nested structure ...)

**Comment by itrich** [comment]
You're absolutely right, I accidentally quoted the wrong option. We should subscribe all members of a nested group directly to the mailing list, which additionally will allow the subgroup's members to edit their subscription preferences in Mailman3.

**Comment by garloff** [comment]
Please review #22.

**Comment by garloff** [comment]
Sidenotes:
* I did implement both options (as it was not hard to do so); the default (`-R 1`) implements option 1 by directly including the members of nested groups into the subscription.
(The recursion depth is 1, so we'll not recurse down further -- however depending on the order of processing, we might still end up with higher level nesting being included, so the end result is not well-defined for several nesting levels in your user directory with `-R 1`. Maybe we should default to `-R 9` or so?)
* `-R 0` switches the nestedGroup processing off.
* `-R -1` switches to option 1: We would subscribe MLs to MLs to reflect the nestedGroup structure.

**Comment by garloff** [comment]
Closed by merged PR#22.
